#!/usr/bin/env python3
"""Run Daily newspaper pipeline, verify PNG, build video, send both to Feishu."""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shlex
import subprocess
import sys
import time
from pathlib import Path
from typing import Iterable

HOME = Path.home()
DAILY_DIR = HOME / "projects" / "Daily"
RUN_ALL = DAILY_DIR / "run_all.sh"
BASE_DIR = Path("/mnt/e/每日新中国")
VIDEO_SCRIPT_DIR = HOME / ".hermes" / "skills" / "productivity" / "daily-china-news-video" / "scripts"
BUILD_FULL = VIDEO_SCRIPT_DIR / "build_full.py"
GEN_INTRO = VIDEO_SCRIPT_DIR / "gen_intro_bg_once.py"
ENV_PATH = HOME / ".hermes" / ".env"
LOG_PREFIX = "[daily-feishu]"

CATEGORY_LABELS = {
    "世界性科研突破": "科研",
    "科技产业升级": "科技",
    "农业与粮食安全": "农业",
    "扶贫与民生改善": "民生",
    "基础设施成就": "基建",
    "能源突破": "能源",
    "医疗健康突破": "医疗",
    "材料与制造突破": "制造",
    "国防军事进展": "军事",
}


def log(msg: str) -> None:
    print(f"{LOG_PREFIX} {msg}", flush=True)


def run(cmd: list[str], *, cwd: Path | None = None, timeout: int | None = None,
        sensitive: bool = False) -> subprocess.CompletedProcess[str]:
    log("$ [sensitive arguments redacted]" if sensitive else "$ " + " ".join(shlex.quote(x) for x in cmd))
    proc = subprocess.run(cmd, cwd=str(cwd) if cwd else None, text=True, capture_output=True, timeout=timeout)
    if proc.stdout and not sensitive:
        print(proc.stdout, end="" if proc.stdout.endswith("\n") else "\n")
    if proc.stderr and not sensitive:
        print(proc.stderr, end="" if proc.stderr.endswith("\n") else "\n", file=sys.stderr)
    if proc.returncode != 0:
        detail = "[sensitive arguments redacted]" if sensitive else " ".join(cmd)
        raise SystemExit(f"Command failed ({proc.returncode}): {detail}")
    return proc


def load_env(path: Path = ENV_PATH) -> dict[str, str]:
    env: dict[str, str] = {}
    if path.exists():
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def today_or_arg(value: str | None) -> str:
    if value:
        dt.datetime.strptime(value, "%Y-%m-%d")
        return value
    return dt.date.today().isoformat()


def issue_name(target: dt.date) -> str:
    units = ["", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十"]
    n = (target - dt.date(2026, 4, 19)).days + 1
    if n <= 0:
        return str(n)
    if n <= 10:
        return "第" + units[n] + "期"
    if n <= 19:
        return "第十" + units[n - 10] + "期"
    if n <= 99:
        return "第" + units[n // 10] + "十" + (units[n % 10] if n % 10 else "") + "期"
    return f"第{n}期"


def expected_png(date_s: str) -> Path:
    target = dt.date.fromisoformat(date_s)
    return BASE_DIR / date_s / f"{date_s}_每日新中国_{issue_name(target)}.png"


def newest_matching(paths: Iterable[Path]) -> Path | None:
    existing = [p for p in paths if p.exists() and p.stat().st_size > 0]
    return max(existing, key=lambda p: p.stat().st_mtime) if existing else None


def find_png(date_s: str, started_at: float) -> Path:
    exact = expected_png(date_s)
    candidates = [exact] + list((BASE_DIR / date_s).glob("*.png"))
    png = newest_matching(candidates)
    if not png:
        raise SystemExit(f"PNG not found for {date_s}; expected {exact}")
    if png.stat().st_mtime < started_at - 60:
        raise SystemExit(f"PNG exists but was not generated by this run: {png}")
    log(f"PNG verified: {png} ({png.stat().st_size} bytes)")
    return png


def strip_emoji(text: str) -> str:
    text = re.sub(r"[\U00010000-\U0010ffff]", "", text)
    return re.sub(r"\s+", " ", text).strip()


def label_from_heading(heading: str) -> str:
    clean = strip_emoji(heading)
    clean = re.sub(r"^[#\s]+", "", clean).strip()
    return CATEGORY_LABELS.get(clean, clean[:4] or "新闻")


def make_prompt(title: str, summary: str, label: str) -> str:
    subject = re.sub(r"^\[[^\]]+\]\s*", "", title).strip()
    source = "Chinese positive news documentary scene"
    return (
        f"{source}, category {label}, {subject}. "
        f"Core context: {summary[:160]}. "
        "Cinematic realistic news photography, hopeful tone, China, wide angle"
    )


def parse_overview(path: Path) -> list[tuple[str, str, str]]:
    if not path.exists():
        raise SystemExit(f"Overview not found: {path}")
    sections: list[tuple[str, str, str]] = []
    current_heading = "新闻"
    current_title: str | None = None
    current_summary: list[str] = []

    def flush() -> None:
        nonlocal current_title, current_summary
        if not current_title or not current_summary:
            return
        summary = "\n".join(current_summary).strip()
        if "栏目留空" in summary or "当日无真实报道" in summary:
            return
        narration = summary
        label = label_from_heading(current_heading)
        sections.append((narration, make_prompt(current_title, summary, label), label))

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        m2 = re.match(r"^##\s+(.+)", line)
        if m2:
            flush()
            current_heading = m2.group(1).strip()
            current_title = None
            current_summary = []
            continue
        m3 = re.match(r"^###\s+(.+)", line)
        if m3:
            flush()
            current_title = m3.group(1).strip()
            current_summary = []
            continue
        if line and not line.startswith("#") and current_title:
            current_summary.append(line)
    flush()
    if not sections:
        raise SystemExit(f"No real news sections parsed from {path}")
    log(f"Parsed {len(sections)} video sections from {path}")
    return sections


def ensure_intro_bg() -> None:
    intro = BASE_DIR / "intro_bg.png"
    if intro.exists() and intro.stat().st_size > 0:
        return
    if not GEN_INTRO.exists():
        raise SystemExit(f"Intro generator missing: {GEN_INTRO}")
    run(["python3", str(GEN_INTRO)], timeout=420)


def build_video(date_s: str, sections: list[tuple[str, str, str]]) -> Path:
    if not BUILD_FULL.exists():
        raise SystemExit(f"Video build script missing: {BUILD_FULL}")
    ensure_intro_bg()
    args = ["python3", str(BUILD_FULL), "--date", date_s, "--sections"]
    args.extend(f"{n}__{p}__{label}" for n, p, label in sections)
    run(args, timeout=7200)
    final = BASE_DIR / date_s / "video" / f"每日新中国_{date_s}_GPT最终版.mp4"
    if not final.exists() or final.stat().st_size <= 0:
        raise SystemExit(f"Video not generated: {final}")

    # ── 完整性验证 ──
    vid_dir = BASE_DIR / date_s / "video"
    n = len(sections)

    for i in range(1, n + 1):
        clip = vid_dir / f"clip_{i:02d}.mp4"
        if not clip.exists() or clip.stat().st_size <= 0:
            raise SystemExit(f"Video incomplete: missing {clip.name}")
        audio = vid_dir / f"audio_{i:02d}.mp3"
        if not audio.exists() or audio.stat().st_size <= 0:
            raise SystemExit(f"Video incomplete: missing {audio.name}")

    probe = subprocess.run(
        ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_format", str(final)],
        capture_output=True, text=True, timeout=10,
    )
    try:
        dur = float(json.loads(probe.stdout)["format"]["duration"])
    except (json.JSONDecodeError, KeyError, ValueError):
        raise SystemExit(f"Video incomplete: ffprobe failed on {final}")
    if dur < 30:
        raise SystemExit(f"Video too short ({dur:.0f}s), likely GPT image failures")

    log(f"Video verified: {final} ({final.stat().st_size} bytes, {dur:.0f}s, {n} clips)")
    return final


def feishu_token(env: dict[str, str]) -> str:
    app_id = env.get("FEISHU_APP_ID")
    app_secret = env.get("FEISHU_APP_SECRET")
    if not app_id or not app_secret:
        raise SystemExit("Missing FEISHU_APP_ID/FEISHU_APP_SECRET in ~/.hermes/.env")
    proc = run([
        "curl", "-s", "-X", "POST",
        "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal",
        "-H", "Content-Type: application/json",
        "-d", json.dumps({"app_id": app_id, "app_secret": app_secret}, ensure_ascii=False),
        "--max-time", "10",
    ], timeout=20, sensitive=True)
    data = json.loads(proc.stdout)
    if data.get("code") != 0:
        raise feishu_error("token", data)
    return data["tenant_access_token"]


def feishu_chat_id(env: dict[str, str]) -> str:
    chat_id = env.get("FEISHU_DAILY_NEWS_CHAT_ID")
    if not chat_id:
        raise SystemExit("Missing FEISHU_DAILY_NEWS_CHAT_ID in ~/.hermes/.env")
    return chat_id


def curl_json(args: list[str], timeout: int) -> dict:
    proc = run(args, timeout=timeout, sensitive=True)
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise SystemExit("Non-JSON Feishu response [content redacted]") from exc


def feishu_error(action: str, data: dict) -> SystemExit:
    return SystemExit(f"Feishu {action} error: code={data.get('code', 'unknown')} [response redacted]")


def send_text(token: str, chat_id: str, text: str) -> None:
    data = curl_json([
        "curl", "-s", "-X", "POST",
        "https://open.feishu.cn/open-apis/im/v1/messages?receive_id_type=chat_id",
        "-H", f"Authorization: Bearer {token}",
        "-H", "Content-Type: application/json",
        "-d", json.dumps({"receive_id": chat_id, "msg_type": "text", "content": json.dumps({"text": text}, ensure_ascii=False)}, ensure_ascii=False),
        "--max-time", "10",
    ], 20)
    if data.get("code") != 0:
        raise feishu_error("text send", data)


def send_image(token: str, chat_id: str, png: Path) -> None:
    up = curl_json([
        "curl", "-s", "-X", "POST",
        "https://open.feishu.cn/open-apis/im/v1/images",
        "-H", f"Authorization: Bearer {token}",
        "-F", "image_type=message",
        "-F", f"image=@{png}",
        "--max-time", "60",
    ], 90)
    if up.get("code") != 0:
        raise feishu_error("image upload", up)
    image_key = up["data"]["image_key"]
    data = curl_json([
        "curl", "-s", "-X", "POST",
        "https://open.feishu.cn/open-apis/im/v1/messages?receive_id_type=chat_id",
        "-H", f"Authorization: Bearer {token}",
        "-H", "Content-Type: application/json",
        "-d", json.dumps({"receive_id": chat_id, "msg_type": "image", "content": json.dumps({"image_key": image_key})}, ensure_ascii=False),
        "--max-time", "10",
    ], 20)
    if data.get("code") != 0:
        raise feishu_error("image send", data)


def send_file(token: str, chat_id: str, path: Path, file_name: str | None = None) -> None:
    up = curl_json([
        "curl", "-s", "-X", "POST",
        "https://open.feishu.cn/open-apis/im/v1/files",
        "-H", f"Authorization: Bearer {token}",
        "-F", "file_type=stream",
        "-F", f"file_name={file_name or path.name}",
        "-F", f"file=@{path}",
        "--max-time", "300",
    ], 360)
    if up.get("code") != 0:
        raise feishu_error("file upload", up)
    file_key = up["data"].get("file_key")
    if not file_key:
        raise SystemExit("Feishu file upload missing file_key [response redacted]")
    data = curl_json([
        "curl", "-s", "-X", "POST",
        "https://open.feishu.cn/open-apis/im/v1/messages?receive_id_type=chat_id",
        "-H", f"Authorization: Bearer {token}",
        "-H", "Content-Type: application/json",
        "-d", json.dumps({"receive_id": chat_id, "msg_type": "file", "content": json.dumps({"file_key": file_key})}, ensure_ascii=False),
        "--max-time", "10",
    ], 20)
    if data.get("code") != 0:
        raise feishu_error("file send", data)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", help="YYYY-MM-DD; defaults to cron run day")
    parser.add_argument("--skip-run-all", action="store_true", help="debug only")
    parser.add_argument("--skip-send", action="store_true", help="debug only")
    args = parser.parse_args()

    date_s = today_or_arg(args.date)
    started_at = time.time()
    log(f"date={date_s}")

    if not RUN_ALL.exists():
        raise SystemExit(f"Missing {RUN_ALL}")
    if not args.skip_run_all:
        run([str(RUN_ALL), "--date", date_s], cwd=DAILY_DIR, timeout=3600)

    png = find_png(date_s, started_at)
    overview = BASE_DIR / date_s / "3新闻_概述.md"
    sections = parse_overview(overview)
    video = build_video(date_s, sections)

    if not args.skip_send:
        env = load_env()
        token = feishu_token(env)
        chat_id = feishu_chat_id(env)
        send_text(token, chat_id, f"每日新中国 {date_s} 已生成，开始发送 PNG 报纸和视频。")
        send_image(token, chat_id, png)
        send_file(token, chat_id, video, video.name)
        log("Feishu delivery completed")
    else:
        log("skip-send enabled; delivery skipped")


def main_with_alert() -> None:
    try:
        main()
    except (Exception, SystemExit) as e:
        # Try to send Feishu alert on failure; don't let alert failure mask original error
        try:
            env = load_env()
            token = feishu_token(env)
            chat_id = feishu_chat_id(env)
            date_s = today_or_arg(None)
            send_text(token, chat_id, f"⚠ 每日新中国 {date_s} 自动化失败：{e}")
            log("Feishu failure alert sent")
        except (Exception, SystemExit) as alert_err:
            log(f"Feishu alert also failed: {alert_err}")
        raise


if __name__ == "__main__":
    main_with_alert()
